apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: <api-name>
  namespace: <system-name>
  title: <Human Readable API Title>
  description: <Short description of the API>
spec:
  owner: default/<owner-name>
  type: openapi
  lifecycle: <experimental|production>
  system: default/<system-name>
  definition:
    $openapi: https://github.com/jouzen/<repo-name>/blob/main/<path-to-openapi-spec>
