apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: <system-name>
  title: <Human Readable Title>
  description: <Short description of what this system does>
  annotations:
    backstage.io/techdocs-ref: dir:. # optional
    github.com/project-slug: jouzen/<repo-name>
  links:
    - title: Slack help channel # optional
      url: <slack-url>
      type: chat
    - title: Logs # optional
      url: <logs-url>
      type: observability
    - title: Metrics # optional
      url: <metrics-url>
      type: observability
spec:
  owner: <owner-name>
  domain: <domain-name>
  maintainedBy: # optional
    - github-<system-name>-admin
    - github-<system-name>-developer
  dependsOn: # optional
    - resource:aws-account/<account-name>
